export enum PidInfoType {
    IndicatorInfo = 'indicator_information',
    MicMetrics = 'microarchitecture_metrics',
    CompareMicMetrics = 'micro_architecture',
    MemoryAccessMetrics = 'memory_access_indicator',
    CpuAffinity = 'cpu_affinity',
    MemoryAffinity = 'memory_affinity',
    CompareMemoryAffinity = 'memory_indicator',
    SystemCall = 'system_call',
    ProcessNumaAllocation = 'process_numa_allocation',
    HotSpotFunc = 'hotspot_function',
    CompareHotSpotFunc = 'hot_spotfunction',
    HotSpotModule = 'hotspot_module',
    OperatedFiles = 'operated_files',
    OperatedFilesResponse = 'file_operation',
    OperatedNetworkPort = 'operated_network_port',
    OperatedNetwork = 'netstat',
}
